config/routes.rb
Spree::Core::Engine.routes.draw do

  # Add your extension routes here
  namespace :admin do
    resources :announcements do
        collection do
          post :update_positions
        end
    end

  end
  resources :announcements
end

app/models/spree/announcement.rb
module Spree
	class Announcement < ActiveRecord::Base
	  def self.current(hidden_ids = nil)
	    result = where("starts_at <= :now and ends_at >= :now", now: Time.zone.now)
	    result = result.where("id not in (?)", hidden_ids) if hidden_ids.present?
	    result
	  end
	end
end

app/controllers/spree/admin/announcements_controller.rb
module Spree
  module Admin
    class AnnouncementsController < ResourceController
      respond_to :html
      def new 
        @announcement = Spree::Announcement.new
      end

      def edit
        @announcement = Spree::Announcement.find(params[:id])
      end

      def create
        @announcement = Spree::Announcement.new(announcement_params)
        if @announcement.save
         redirect_to root_path, notice: 'Announcement was successfully created.'
         else
          render action: 'new'
        end
      end

      def hide
        ids = [params[:id], *cookies.signed[:hidden_announcement_ids]]
        cookies.permanent.signed[:hidden_announcement_ids] = ids
        respond_to do |format|
          format.html { redirect_to :back }
          format.js
        end
      end

    private

      def announcement_params
          params.require(:announcement).permit(
            :message,
            :starts_at,
            :ends_at
          )
      end

    end
  end
end

app/views/spree/admin/announcements/index.html.erb
<% content_for :page_actions do %>
  <%= button_link_to t('spree_announcement.new_announcement'), new_object_url, { class: 'btn-success', icon: 'add', id: 'admin_new_announcement_link' } %>
<% end %>
<% content_for :page_title do %>
  <%= t('spree_announcement.title') %>
<% end %>
<% announcements = @announcements.where.not(position: nil) %>
<%# announcements = @announcements.all %>
<h3>Announcements</h3>
<table class="table sortable" id="listing_announcements" data-hook data-sortable-link="<%= update_positions_admin_announcements_url %>">
  <thead>
    <tr data-hook="admin_announcements_index_headers">
      <th><%= Spree.t(:published) %></th>
      <th data-hook="admin_announcements_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% announcements.each do |announcement| %>
      <tr id="<%= spree_dom_id announcement %>" data-hook="admin_announcements_index_rows">
        <td><%= announcement.message %></td>
        <td><%= announcement.published ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
        <td data-hook="admin_announcements_index_row_actions" class="actions text-right">
          <%= link_to_edit announcement, no_text: true, class: 'edit' %>
          &nbsp;
          <%= link_to_delete announcement, no_text: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/announcements/new.html.erb
<h2 class="form_title">Announcement</h2>
<%= form_for [:admin, @announcement] do |f| %>
  <div class="form-inputs row">
    <div class="col-md-12">
      <%= f.field_container :message do %>
        <%= f.label :message, t(:message) %><br>
        <%= f.text_field :message, class: 'fullwidth form-control', placeholder: "Write announcement" %>
      <% end %>
    </div>
    <div class="col-md-6 starts_at">
      <%= f.field_container :starts_at do %>
        <%= f.label :starts_at, t(:starts_at) %><br>
        <%= f.text_field :starts_at, class: 'fullwidth form-control', placeholder: "Starts at" %>
      <% end %>
    </div>  
    <div class="col-md-6 ends_at">
      <%= f.field_container :ends_at do %>
        <%= f.label :ends_at, t(:ends_at) %><br>
        <%= f.text_field :ends_at, class: 'fullwidth form-control', placeholder: "Ends at" %>
      <% end %>
    </div>
  </div>
      
    <div class="form-actions">
      <%= f.submit 'Create', :data => {:'disable-with' => "Creating"}, class: "btn btn-success"  %>
    </div>

  </div>
<% end %>

app/views/spree/announcements/hide.js.erb
$("#announcement_<%= j params[:id] %>").remove();

app/views/spree/shared/_announcements.html.erb
<% announcements = Spree::Announcement.all %>
<div class="prommotion-topbar">
	<div class="prommotion-topbar__text container">
	  <% announcements.each_with_index do |message, index| %>
	      <span><%= message.message %></span>
	  <% end %>
  	</div>
</div>